services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.18.4
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
